### ISSUE TITLE
Loading citeseq matrix

### ISSUE THREAD

**Issue by mjseignon** [wflynny/multiseq-py#1] opened 2021-03-31 15:22 UTC
I'm truing to load information from the umi_count folder and I'm getting the error below. 
I'm not sure why string is the issue since sc.read_mtx() is also reading path as str 

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-15-1fbc38240d17> in <module>()
> ----> 1 tags = multiseq.load_citeseq_count_matrix('/path/to/umi_count/')
> 
> /home/seignm/.local/lib/python3.6/site-packages/multiseq/readwrite.py in load_citeseq_count_matrix(path)
>       9 
>      10 def load_citeseq_count_matrix(path: Union[Path, str]) -> AnnData:
> ---> 11     raw_tags = read_mtx(path / "matrix.mtx.gz").T
>      12     var = pd.read_csv(path / "features.tsv.gz", header=None, index_col=0)
>      13     var.index.name = None
> 
> TypeError: unsupported operand type(s) for /: 'str' and 'str'

**Comment by wflynny** [comment] 2021-03-31 16:03
Fixed on main branch.

@mjseignon, `path / "file.name"` is only valid when `isinstance(path, Path)`.  In this case `isinstance(path, str)` was causing the error.

**Closed as completed by wflynny** 2021-03-31 16:03 UTC

**Comment by mjseignon** [comment] 2021-03-31 19:02
I'm getting same error. Looks like
Function still has [Path,str] instead of [Path, path]

**Comment by wflynny** [comment] 2021-03-31 19:12
`path: Union[Path, str]` is the type hint (meaning `path` can be either str or Path).

Did you git pull and restart your kernel?

**Comment by mjseignon** [comment] 2021-03-31 19:14
Yep I restarted my kernel and pip installed again

**Comment by wflynny** [comment] 2021-03-31 20:16
Hmm, I can't reproduce this.  I just created and pushed some small test data along with a test.  Could you try cloning and run `pytest` from the repo root, and report if the tests fail?

**Comment by mjseignon** [comment] 2021-03-31 20:48
I'm not sure how to do this. 
I did this post cloning:
import test 

I tried:
multiseq.load_citeseq_count_matrix('test/test-data')

I qet the same error

**Comment by mjseignon** [comment] 2021-03-31 20:50
![Capture](https://user-images.githubusercontent.com/38838373/113209518-2c60c100-9241-11eb-9c06-075b2f1a58dc.PNG)

**Comment by wflynny** [comment] 2021-03-31 21:07
From your traceback, it doesn't look like the newest version is there.  Line 11 in `multiseq.readwrite.load_citeseq_count_matrix` looks like [path = Path(path)](https://github.com/wflynny/multiseq-py/blob/112c349951bde42d53016de3e002a439260055d5/multiseq/readwrite.py#L11)

This should work to run the tests:
```
git clone git@github.com:wflynny/multiseq-py.git
cd multiseq-py
pip install .
pytest
```
The pip install should install the python module `pytest`.

**Comment by mjseignon** [comment] 2021-03-31 21:45
function does not fail anymore. I think cloning instead of pip install the repository did the trick with updating the code.

For the test:
no module, no pip, in commandline. I'm on elion026.
I try `>pip install .` in notebook. It installs, but I can't call the test.

**Comment by wflynny** [comment] 2021-03-31 22:10
That code is bash code, so either do (in your notebook)
```
%%bash
cd /path/to/multiseq-py
pytest
```
or
```
!pytest
```
Or do it in the shell.

The other question is, are you installing it into the same environment/container/whatever that's running your jupyterlab?
